metadata:
  name: app-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: jenkins-tp.cours-datascientest-lbaxel.cloudns.be
    http:
      paths:
        # Path movies
        - path: /api/v1/movies
          pathType: Prefix
          backend:
             service:
              name: fastapi-movie-service
              port:
                number: 8000
        # Path casts
        - path: /api/v1/casts
          pathType: Prefix
          backend:
             service:
              name: fastapi-cast-service
              port:
                number: 8000
